sudo: required
language: ruby

before_install:
- gem update --system
- gem --version
- gem install bundler
- bundle --version

sevices:
  - docker

addons:
  apt:
    packages:
    - docker-ce

jobs:
  include:
    - stage: plain go app tests
      script: bundle install && bundle exec bugsnag-maze-runner -c features/plain_features
      env:
        matrix:
          - GO_VERSION=1.11
          - GO_VERSION=1.10
          - GO_VERSION=1.9
          - GO_VERSION=1.8
          - GO_VERSION=1.7
    - stage: net/http tests
      script: bundle install && bundle exec bugsnag-maze-runner -c features/net_http_features
      env:
        matrix:
          - GO_VERSION=1.11
          - GO_VERSION=1.10
          - GO_VERSION=1.9
          - GO_VERSION=1.8
          - GO_VERSION=1.7
    
stages:
  - plain go app tests
  - net/http tests


