sudo: required
language: ruby

before_install:
- gem update --system
- gem --version
- gem install bundler
- bundle --version

script:
- bundle install
- bundle exec bugsnag-maze-runner -c features/gintest.feature

env:
  - GO_VERSION=1.11
  - GO_VERSION=1.10
  - GO_VERSION=1.9
  - GO_VERSION=1.8
  - GO_VERSION=1.7

sevices:
  - docker

stages:
  - gin

addons:
  apt:
    packages:
    - docker-ce
    


