sudo: required
language: ruby

before_install:
- gem update --system
- gem --version
- gem install bundler
- bundle --version

install:
- bundle install

sevices:
  - docker

addons:
  apt:
    packages:
    - docker-ce

jobs:
  include:
    - stage: plain go app tests
      script: make testplain
      env: GO_VERSION=1.11
    - if: branch = master
      script: make testplain
      env: GO_VERSION=1.10
    - if: branch = master
      script: make testplain
      env: GO_VERSION=1.9
    - if: branch = master
      script: make testplain
      env: GO_VERSION=1.8
    - if: branch = master
      script: make testplain
      env: GO_VERSION=1.7


    - stage: net/http tests
      script: make testnethttp
      env: GO_VERSION=1.11
    - if: branch = master
      script: make testnethttp
      env: GO_VERSION=1.10
    - if: branch = master
      script: make testnethttp
      env: GO_VERSION=1.9
    - if: branch = master
      script: make testnethttp
      env: GO_VERSION=1.8
    - if: branch = master
      script: make testnethttp
      env: GO_VERSION=1.7

      
    - stage: gin tests (v1.3.0)
      script: make testgin
      env: 
        - GO_VERSION=1.11
        - GIN_VERISON=v1.3.0
    - if: branch = master
      script: make testgin
      env: 
        - GO_VERSION=1.10
        - GIN_VERISON=v1.3.0
    - if: branch = master
      script: make testgin
      env: 
        - GO_VERSION=1.9
        - GIN_VERISON=v1.3.0
    - if: branch = master
      script: make testgin
      env: 
        - GO_VERSION=1.8
        - GIN_VERISON=v1.3.0
    - if: branch = master
      script: make testgin
      env: 
        - GO_VERSION=1.17
        - GIN_VERISON=v1.3.0
