sudo: false
language: ruby

before_install:
- gem update --system
- gem --version
- gem install bundler
- bundle --version

script:
  - bundle install
  - bundle exec bugsnag-maze-runner

jobs:
  include:
    - stage: test
      addons:
        apt:
          packages:
          - docker-ce
      sudo: required
      sevices:
      - docker
      rmv: 2.4.1
      script: bundle exec bugsnag-maze-runner -c features/gintest.feature


